name: "On every commit to main, run integration and unittests."

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install test dependencies
        run: |
          python -m pip install -r test-requirements.txt
      - name: Test with pytest
        run: |
          PYTHONPATH=$(pwd) pytest tests/unit/ tests/integration