name: "On every PR opened, run unittests."

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Install test dependencies
        run: |
          python -m pip install -r test-requirements.txt
      - name: Test with pytest
        run: |
          PYTHONPATH=$(pwd) pytest tests/unit/